# Site wide configuration

title:            Abhinav Saxena
locale:           en_US
url:              http://www.abhinavsaxena.com
#url:              http://localhost:4000


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Abhinav Saxena
  avatar: abhinav.jpeg
  bio: "a body of clay, a mind full of play, a moment's life - that is me"
  email: 
  disqus-shortname: shabdabhinav
  twitter: abhinav
  facebook: abhinavs
  google:
    plus: #username
    analytics: 
    verify: 
    ad-client: 
    ad-slot: 
  bing-verify: 
  github: abhinavs
  stackoverflow: #http://stackoverflow.com/users/123456/username
  linkedin: abhinavs
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
